apiVersion: tf.tungstenfabric.io/v1alpha1
kind: ConfigCluster
metadata:
<<<<<<< HEAD
  name: config-cluster-1
spec:
  size: 1
  hostnetwork: false
  imagepullpolicy: "Always"
  apiImage: "docker.io/michaelhenkel/contrail-controller-config-api:5.1.1-dev3"
  deviceManagerImage: "docker.io/michaelhenkel/contrail-controller-config-devicemgr:5.1.1-dev3"
  schemaTransformerImage: "docker.io/michaelhenkel/contrail-controller-config-schema:5.1.1-dev3"
  serviceMonitorImage: "docker.io/michaelhenkel/contrail-controller-config-svcmonitor:5.1.1-dev3"
  analyticsApiImage: "docker.io/michaelhenkel/contrail-analytics-api:5.1.1-dev3"
  collectorImage: "docker.io/michaelhenkel/contrail-analytics-collector:5.1.1-dev3"
  redisImage: "docker.io/michaelhenkel/contrail-external-redis:5.1.1-dev3"
  nodeManagerImage: "docker.io/michaelhenkel/contrail-nodemgr:5.1.1-dev3"
  nodeInitImage: "docker.io/michaelhenkel/contrail-node-init:5.1.1-dev3"
  statusImage: "docker.io/michaelhenkel/contrail-status:5.1.1-dev3"
  cassandraClusterName: "cassandra-cluster-1"
  zookeeperClusterName: "zookeeper-cluster-1"
  rabbitmqClusterName: "rabbitmq-cluster-1"
  configClusterName: "config-cluster-1"
=======
  name: cluster-1
spec:
  type: deployment
  containers:
    - name: api
      logvolumepath: "/var/log/contrail"
      resourceconfigmap: true
    - name: devicemanager
      logvolumepath: "/var/log/contrail"
      resourceconfigmap: true
    - name: schematransformer
      logvolumepath: "/var/log/contrail"
      resourceconfigmap: true
    - name: servicemonitor
      logvolumepath: "/var/log/contrail"
      resourceconfigmap: true
    - name: analyticsapi
      logvolumepath: "/var/log/contrail"
      resourceconfigmap: true
    - name: collector
      logvolumepath: "/var/log/contrail"
      resourceconfigmap: true
    - name: redis
      logvolumepath: "/var/log/redis"
      datavolumepath: "/var/lib/redis"
      resourceconfigmap: true
    - name: nodemanagerconfig
      logvolumepath: "/var/log/contrail"
      unixsocketvolume: true
      resourceconfigmap: true
      env:
        "NODE_TYPE": "config"
        "DOCKER_HOST": "unix://mnt/docker.sock"
    - name: nodemanageranalytics
      logvolumepath: "/var/log/contrail"
      unixsocketvolume: true
      resourceconfigmap: true
      env:
        "NODE_TYPE": "analytics"
        "DOCKER_HOST": "unix://mnt/docker.sock"
  initcontainers:
    - name: init
      statusvolume: true
      command: ["sh","-c","until grep ready /tmp/podinfo/pod_labels > /dev/null 2>&1; do sleep 1; done"]   
    - name: nodeinit
      privileged: true
      hostusrbinvolume: true
      resourceconfigmap: true

>>>>>>> v0.0.4
