apiVersion: tf.tungstenfabric.io/v1alpha1
kind: KubemanagerCluster
metadata:
<<<<<<< HEAD
  name: kubemanager-cluster-1
spec:
  # Add fields here
  size: 1
  hostnetwork: false
  imagepullpolicy: "Always"
  kubeManagerImage: "docker.io/michaelhenkel/contrail-kubernetes-kube-manager:5.1.1-dev3"
  nodeInitImage: "docker.io/michaelhenkel/contrail-node-init:5.1.1-dev3"
  statusImage: "docker.io/michaelhenkel/contrail-status:5.1.1-dev3"
  cassandraClusterName: "cassandra-cluster-1"
  rabbitmqClusterName: "rabbitmq-cluster-1"
  configClusterName: "config-cluster-1"
  zookeeperClusterName: "zookeeper-cluster-1"
  kubernetesApiServer: "10.96.0.1"
  kubernetesApiPort: "443"
  kubernetesPodSubnets: "10.32.0.0/12"
  kubernetesServiceSubnets: "10.96.0.0/12"
  kubernetesClusterName: "k8s-default"
  kubernetesIpFabricForwarding: "true"
  kubernetesIpFabricSnat: "true"
  kubernetesTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
=======
  name: cluster-1
spec:
  type: deployment
  containers:
    - name: kubemanager
      logvolumepath: "/var/log/contrail"
      resourceconfigmap: true
  initcontainers:
    - name: init
      statusvolume: true
      command: ["sh","-c","until grep ready /tmp/podinfo/pod_labels > /dev/null 2>&1; do sleep 1; done"]   
    - name: nodeinit
      privileged: true
      hostusrbinvolume: true
      resourceconfigmap: true

>>>>>>> v0.0.4
