apiVersion: tf.tungstenfabric.io/v1alpha1
kind: ZookeeperCluster
metadata:
  name: cluster-1
spec:
  type: deployment
  containers:
    - name: zookeeper
      logvolumepath: "/var/log/zookeeker"
      datavolumepath: "/var/lib/zookeeper"
