apiVersion: tf.tungstenfabric.io/v1alpha1
kind: RabbitmqCluster
metadata:
  name: cluster-1
spec:
  type: deployment
  containers:
    - name: rabbitmq
      logvolumepath: "/var/log/rabbitmq"
      datavolumepath: "/var/lib/rabbitmq"
