apiVersion: tf.tungstenfabric.io/v1alpha1
kind: CassandraCluster
metadata:
  name: cassandra-cluster-1
spec:
  # Add fields here
  size: 1
  hostnetwork: false
  image: "docker.io/michaelhenkel/contrail-external-cassandra:5.1.1-dev3"
  imagepullpolicy: "Always"
  startrpc: "true"
  listenaddress: "auto"
  port: "9160"
  cqlport: "9042"
  sslstorageport: "7001"
  storageport: "7000"
  jmxport: "7199"
