apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configclusters.tf.tungstenfabric.io
spec:
  group: tf.tungstenfabric.io
  names:
    kind: ConfigCluster
    listKind: ConfigClusterList
    plural: configclusters
    singular: configcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            analyticsApiImage:
              type: string
            apiImage:
              type: string
            collectorImage:
              type: string
            deviceManagerImage:
              type: string
            hostnetwork:
              type: string
            image:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            imagepullpolicy:
              type: string
            nodeInitImage:
              type: string
            nodeManagerImage:
              type: string
            redisImage:
              type: string
            schemaTransformerImage:
              type: string
            serviceMonitorImage:
              type: string
            size:
              type: string
            statusImage:
              type: string
          required:
          - image
          - hostnetwork
          - imagepullpolicy
          type: object
        status:
          properties:
            nodes:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
