apiVersion: tf.tungstenfabric.io/v1alpha1
kind: CassandraCluster
metadata:
  name: cluster-1
spec:
  type: deployment
  containers:
    - name: cassandra
      logvolumepath: "/var/log/cassandra"
      datavolumepath: "/var/lib/cassandra"

