apiVersion: tf.tungstenfabric.io/v1alpha1
kind: WebuiCluster
metadata:
  name: cluster-1
spec:
  type: deployment
  containers:
    - name: webuiweb
      logvolumepath: "/var/log/contrail"
      resourceconfigmap: true
    - name: webuijob
      logvolumepath: "/var/log/contrail"
      resourceconfigmap: true
  initcontainers:
    - name: init
      statusvolume: true
      command: ["sh","-c","until grep ready /tmp/podinfo/pod_labels > /dev/null 2>&1; do sleep 1; done"]   
    - name: nodeinit
      privileged: true
      hostusrbinvolume: true
      resourceconfigmap: true

