apiVersion: tf.tungstenfabric.io/v1alpha1
kind: ConfigCluster
metadata:
  name: config-cluster-1
spec:
  size: 1
  hostnetwork: false
  imagepullpolicy: "Always"
  apiImage: "docker.io/michaelhenkel/contrail-controller-config-api:5.1.1-dev3"
  deviceManagerImage: "docker.io/michaelhenkel/contrail-controller-config-devicemgr:5.1.1-dev3"
  schemaTransformerImage: "docker.io/michaelhenkel/contrail-controller-config-schema:5.1.1-dev3"
  serviceMonitorImage: "docker.io/michaelhenkel/contrail-controller-config-svcmonitor:5.1.1-dev3"
  analyticsApiImage: "docker.io/michaelhenkel/contrail-analytics-api:5.1.1-dev3"
  collectorImage: "docker.io/michaelhenkel/contrail-analytics-collector:5.1.1-dev3"
  nodeManagerImage: "docker.io/michaelhenkel/contrail-nodemgr:5.1.1-dev3"
  nodeInitImage: "docker.io/michaelhenkel/contrail-node-init:5.1.1-dev3"
  statusImage: "docker.io/michaelhenkel/contrail-status:5.1.1-dev3"
  cassandraClusterName: "cassandra-cluster-1"
  zookeeperClusterName: "zookeeper-cluster-1"
  rabbitmqClusterName: "rabbitmq-cluster-1"
  configClusterName: "config-cluster-1"

