apiVersion: tf.tungstenfabric.io/v1alpha1
kind: WebuiCluster
metadata:
  name: cluster-1
spec:
  type: deployment
  containers:
    - name: webuiweb
      logvolumepath: "/var/log/contrail"
    - name: webuijob
      logvolumepath: "/var/log/contrail"
