apiVersion: tf.tungstenfabric.io/v1alpha1
kind: CassandraCluster
metadata:
  name: cluster-1
spec:
  type: deployment
  containers:
    - name: cassandra
      logvolumepath: "/var/log/cassandra"
      datavolumepath: "/var/lib/cassandra"
  initcontainers:
    - name: init
      statusvolume: true
      command: ["sh","-c","until grep ready /tmp/podinfo/pod_labels > /dev/null 2>&1; do sleep 1; done"]   

