apiVersion: tf.tungstenfabric.io/v1alpha1
kind: KubemanagerCluster
metadata:
  name: cluster-1
spec:
  type: deployment
  containers:
    - name: kubemanager
      logvolumepath: "/var/log/contrail"

