apiVersion: tf.tungstenfabric.io/v1alpha1
kind: Vrouter
metadata:
  name: cluster-1
spec:
  type: daemonset
  containers:
    - name: agent
      logvolumepath: "/var/log/contrail"
      devvolume: true
      networkscriptsvolume: true
      hostbinvolume: true
      usrsrcvolume: true
      libmodulesvolume: true
      varlibcontrailvolume: true
      varcrashesvolume: true
      privileged: true
      lifecyclescript: ["/cleanup.sh"]
  initcontainers:  
    - name: nodeinit
      privileged: true
      hostusrbinvolume: true
    - name: vrouterkernelinit
      privileged: true
      hostusrbinvolume: true
      usrsrcvolume: true
      libmodulesvolume: true
      networkscriptsvolume: true
      hostbinvolume: true
    - name: vrouternicinit
      privileged: true
      hostusrbinvolume: true
      usrsrcvolume: true
      networkscriptsvolume: true   
      hostbinvolume: true  
    - name: vroutercniinit
      privileged: true
      hostusrbinvolume: true
      varlibcontrailvolume: true
      etccnivolume: true
      optcnibinvolume: true
      varlogcontrailcnivolume: true
      logvolumepath: "/var/log/contrail"