apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubemanagerclusters.tf.tungstenfabric.io
spec:
  group: tf.tungstenfabric.io
  names:
    kind: KubemanagerCluster
    listKind: KubemanagerClusterList
    plural: kubemanagerclusters
    singular: kubemanagercluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            containers:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  datavolumepath:
                    type: string
                  env:
                    additionalProperties:
                      type: string
                    type: object
                  etccontrailvolume:
                    type: boolean
                  hostuserbinvolume:
                    type: boolean
                  image:
                    type: string
                  imagepullpolicy:
                    type: string
                  logvolumepath:
                    type: string
                  name:
                    type: string
                  privileged:
                    type: boolean
                  unixsocketvolume:
                    type: boolean
                required:
                - name
                - imagepullpolicy
                - logvolumepath
                - datavolumepath
                - unixsocketvolume
                - hostuserbinvolume
                - etccontrailvolume
                - privileged
                - env
                type: object
              type: array
          required:
          - containers
          type: object
        status:
          properties:
            nodes:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
