apiVersion: zookeeper.tungstenfabric.io/v1alpha1
kind: Zookeeper
metadata:
  name: zookeeper
spec:
  size: 3
  hostnetwork: false
  image: "docker.io/michaelhenkel/contrail-external-zookeeper:5.1.1-dev3"
  imagepullpolicy: "Always"
  zookeeperport: "2181"
  zookeeperports: "2888-3888"

