apiVersion: zookeeper.tungstenfabric.io/v1alpha1
kind: Zookeeper
metadata:
  name: zookeeper
spec:
  # Add fields here
  size: 3
  hostnetwork: true
  registry: docker.io/michaelhenkel
  version: 5.1.1-dev3
