apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: tungstenfabric-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - tungstenfabric-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - tf.tungstenfabric.io
  resources:
  - '*'
  - vrouters
  - cassandraclusters
  - zookeeperclusters
  - rabbitmqclusters
  - configclusters
  - controlclusters
  - kubemanagerclusters
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tungstenfabric-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - events
  - configmaps
  verbs:
  - get
  - list
  - update
  - watch
  - patch
- apiGroups:
  - apiextensions.k8s.io
  - extensions
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - list
  - update
  - watch
  - delete
  - patch
- apiGroups:
  - rbac
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - create
  - list
  - update
  - watch
  - delete
  - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tungstenfabric-operator
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tungstenfabric-operator
subjects:
- kind: ServiceAccount
  name: tungstenfabric-operator
roleRef:
  kind: Role
  name: tungstenfabric-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tungstenfabric-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: tungstenfabric-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: tungstenfabric-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tungstenfabricconfigs.tf.tungstenfabric.io
spec:
  group: tf.tungstenfabric.io
  names:
    kind: TungstenfabricConfig
    listKind: TungstenfabricConfigList
    plural: tungstenfabricconfigs
    singular: tungstenfabricconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          properties:
            nodes:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tungstenfabric-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tungstenfabric-operator
  template:
    metadata:
      labels:
        name: tungstenfabric-operator
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      serviceAccountName: tungstenfabric-operator
      hostNetwork: true
      containers:
        - name: tungstenfabric-operator
          image: docker.io/michaelhenkel/tungstenfabric-operator:v0.0.1
          command:
          - tungstenfabric-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "tungstenfabric-operator"
