---
apiVersion: tf.tungstenfabric.io/v1alpha1
kind: TungstenfabricManager
metadata:
  name: cluster-1
spec:
  images:
    nodemanager: "docker.io/michaelhenkel/contrail-nodemgr:5.1.1-dev3"
    nodemanagerconfig: "docker.io/michaelhenkel/contrail-nodemgr:5.1.1-dev3"
    nodemanageranalytics: "docker.io/michaelhenkel/contrail-nodemgr:5.1.1-dev3"
    nodeinit: "docker.io/michaelhenkel/contrail-node-init:5.1.1-dev3"
    status: "docker.io/michaelhenkel/contrail-status:5.1.1-dev3"
    api: "docker.io/michaelhenkel/contrail-controller-config-api:5.1.1-dev3"
    devicemanager: "docker.io/michaelhenkel/contrail-controller-config-devicemgr:5.1.1-dev3"
    schematransformer: "docker.io/michaelhenkel/contrail-controller-config-schema:5.1.1-dev3"
    servicemonitor: "docker.io/michaelhenkel/contrail-controller-config-svcmonitor:5.1.1-dev3"
    analyticsapi: "docker.io/michaelhenkel/contrail-analytics-api:5.1.1-dev3"
    collector: "docker.io/michaelhenkel/contrail-analytics-collector:5.1.1-dev3"
    redis: "docker.io/michaelhenkel/contrail-external-redis:5.1.1-dev3"
    control: "docker.io/michaelhenkel/contrail-controller-control-control:5.1.1-dev3"
    named: "docker.io/michaelhenkel/contrail-controller-control-named:5.1.1-dev3"
    dns: "docker.io/michaelhenkel/contrail-controller-control-dns:5.1.1-dev3"
    kubemanager: "docker.io/michaelhenkel/contrail-kubernetes-kube-manager:5.1.1-dev3"
    cassandra: "docker.io/michaelhenkel/contrail-external-cassandra:5.1.1-dev3"
    zookeeper: "docker.io/michaelhenkel/contrail-external-zookeeper:5.1.1-dev3"
    rabbitmq: "docker.io/michaelhenkel/contrail-external-rabbitmq:5.1.1-dev3"
    vrouterkernelinit: "docker.io/michaelhenkel/contrail-vrouter-kernel-init:5.1.1-dev3"
    vrouternicinit: "docker.io/michaelhenkel/contrail-vrouter-nic-init:5.1.1-dev3"
    vroutercni: "docker.io/michaelhenkel/contrail-kubernetes-cni-init:5.1.1-dev3"
    vrouteragent: "docker.io/michaelhenkel/contrail-vrouter-agent:5.1.1-dev3"
    webuiWeb: "docker.io/michaelhenkel/contrail-controller-webui-web:5.1.1-dev3"
    webuiJob: "docker.io/michaelhenkel/contrail-controller-webui-job:5.1.1-dev3"
  general:
    size: "1"
    hostNetwork: "false"
    pullPolicy: "Always"
    aaaMode: ""
    authMode: ""
    cloudAdminRole: ""
    globalReadOnlyRole: ""
  kubemanagerConfig:
    size: "1"
    service:
    KUBERNETES_API_SERVER: "10.96.0.1"
    KUBERNETES_API_SECURE_PORT: "443"
    KUBERNETES_POD_SUBNETS: "10.32.0.0/12"
    KUBERNETES_SERVICE_SUBNETS: "10.96.0.0/12"
    KUBERNETES_CLUSTER_NAME: "k8s-default"
    KUBERNETES_IP_FABRIC_FORWARDING: "true"
    KUBERNETES_IP_FABRIC_SNAT: "true"
    K8S_TOKEN_FILE: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  cassandraConfig:
    size: "1"
    CASSANDRA_LISTEN_ADDRESS: "auto"
    CASSANDRA_PORT: "9160"
    CASSANDRA_CQL_PORT: "9042"
    CASSANDRA_SSL_STORAGE_PORT: "7001"
    CASSANDRA_STORAGE_PORT: "7000"
    CASSANDRA_JMX_LOCAL_PORT: "7199"
    CASSANDRA_START_RPC: "true"
    CASSANDRA_CLUSTER_NAME: "ContrailConfigDB"
    NODE_TYPE: "config-database"
  zookeeperConfig:
    size: "1"
    ZOOKEEPER_PORT: "2181"
    ZOOKEEPER_PORTS: "2888:3888"
    NODE_TYPE: "config-database"
  rabbitmqConfig:
    size: "1"
    RABBITMQ_NODE_PORT: "5673"
    RABBITMQ_ERLANG_COOKIE: "47EFF3BB-4786-46E0-A5BB-58455B3C2CB4"
    NODE_TYPE: "config-database"
  configConfig:
    size: "1"
  controlConfig:
    size: "1"
  webuiConfig:
    size: "1"
    BLA: "BLA"
