---
apiVersion: tf.tungstenfabric.io/v1alpha1
kind: CassandraCluster
metadata:
  name: cluster-1
spec:
  containers:
    - name: cassandra
      logvolumepath: "/var/log/cassandra"
      datavolumepath: "/var/lib/cassandra"

---
apiVersion: tf.tungstenfabric.io/v1alpha1
kind: ConfigCluster
metadata:
  name: cluster-1
spec:
  containers:
    - name: api
      logvolumepath: "/var/log/contrail"
    - name: devicemanager
      logvolumepath: "/var/log/contrail"
    - name: schematransformer
      logvolumepath: "/var/log/contrail"
    - name: servicemonitor
      logvolumepath: "/var/log/contrail"
    - name: analyticsapi
      logvolumepath: "/var/log/contrail"
    - name: collector
      logvolumepath: "/var/log/contrail"
    - name: redis
      logvolumepath: "/var/log/redis"
      datavolumepath: "/var/lib/redis"
    - name: nodemanagerconfig
      logvolumepath: "/var/log/contrail"
      unixsocketvolume: true
      env:
        "NODE_TYPE": "config"
        "DOCKER_HOST": "unix://mnt/docker.sock"
    - name: nodemanageranalytics
      logvolumepath: "/var/log/contrail"
      unixsocketvolume: true
      env:
        "NODE_TYPE": "analytics"
        "DOCKER_HOST": "unix://mnt/docker.sock"

---
apiVersion: tf.tungstenfabric.io/v1alpha1
kind: ControlCluster
metadata:
  name: cluster-1
spec:
  containers:
    - name: control
      logvolumepath: "/var/log/contrail"
    - name: named
      logvolumepath: "/var/log/contrail"
      privileged: true
      etccontrailvolume: true
    - name: dns
      logvolumepath: "/var/log/contrail"
      etccontrailvolume: true
    - name: nodemanager
      logvolumepath: "/var/log/contrail"
      unixsocketvolume: true
      env:
        "NODE_TYPE": "control"
        "DOCKER_HOST": "unix://mnt/docker.sock"
---
apiVersion: tf.tungstenfabric.io/v1alpha1
kind: KubemanagerCluster
metadata:
  name: cluster-1
spec:
  containers:
    - name: kubemanager
      logvolumepath: "/var/log/contrail"

---
apiVersion: tf.tungstenfabric.io/v1alpha1
kind: RabbitmqCluster
metadata:
  name: cluster-1
spec:
  containers:
    - name: rabbitmq
      logvolumepath: "/var/log/rabbitmq"
      datavolumepath: "/var/lib/rabbitmq"
---
apiVersion: tf.tungstenfabric.io/v1alpha1
kind: Vrouter
metadata:
  name: cluster-1
---
apiVersion: tf.tungstenfabric.io/v1alpha1
kind: WebuiCluster
metadata:
  name: cluster-1
spec:
  type: deployment
  containers:
    - name: webuiWeb
      image: docker.io/michaelhenkel/contrail-controller-webui-web:5.1.1-dev3
    - name: webuiJob
---
apiVersion: tf.tungstenfabric.io/v1alpha1
kind: ZookeeperCluster
metadata:
  name: cluster-1
spec:
  containers:
    - name: zookeeper
      logvolumepath: "/var/log/zookeeker"
      datavolumepath: "/var/lib/zookeeper"
---
