apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tungstenfabric-operator
rules:
  - apiGrous:
    - "*"
    resources:
    - "*"
    verbs:
    - "*"
#- apiGroups:
#  - ""
#  resources:
#  - pods
#  - services
#  - endpoints
#  - events
#  - configmaps
#  verbs:
#  - get
#  - list
#  - update
#  - watch
#  - patch
#- apiGroups:
#  - apiextensions.k8s.io
#  - extensions
#  resources:
#  - customresourcedefinitions
#  verbs:
#  - get
#  - create
#  - list
#  - update
#  - watch
#  - delete
#  - patch
#- apiGroups:
#  - rbac
#  - rbac.authorization.k8s.io
#  resources:
#  - clusterroles
#  - clusterrolebindings
#  verbs:
#  - get
#  - create
#  - list
#  - update
#  - watch
#  - delete
#  - patch
