apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: tungstenfabric-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
<<<<<<< HEAD
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
=======
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
>>>>>>> v0.0.4
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - tungstenfabric-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
<<<<<<< HEAD
  - cassandra.tungstenfabric.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - zookeeper.tungstenfabric.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rabbitmq.tungstenfabric.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - redis.tungstenfabric.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config.tungstenfabric.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - tf.tungstenfabric.io
  resources:
  - '*'
=======
  - tf.tungstenfabric.io
  resources:
  - '*'
  - vrouters
>>>>>>> v0.0.4
  - cassandraclusters
  - zookeeperclusters
  - rabbitmqclusters
  - configclusters
<<<<<<< HEAD
  - analyticsclusters
  - controlclusters
  - kubemanagerclusters
  - vrouters
=======
  - controlclusters
  - kubemanagerclusters
  - webuiclusters
  - tungstenfabricmanagers
>>>>>>> v0.0.4
  verbs:
  - '*'
