apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: tungstenfabric-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - tungstenfabric-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - tf.tungstenfabric.io
  resources:
  - '*'
  - vrouters
  - cassandraclusters
  - zookeeperclusters
  - rabbitmqclusters
  - configclusters
  - controlclusters
  - kubemanagerclusters
  - webuiclusters
  - tungstenfabricmanagers
  verbs:
  - '*'
