// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.TungstenfabricConfig":       schema_pkg_apis_tf_v1alpha1_TungstenfabricConfig(ref),
		"github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.TungstenfabricConfigSpec":   schema_pkg_apis_tf_v1alpha1_TungstenfabricConfigSpec(ref),
		"github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.TungstenfabricConfigStatus": schema_pkg_apis_tf_v1alpha1_TungstenfabricConfigStatus(ref),
		"github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.Vrouter":                    schema_pkg_apis_tf_v1alpha1_Vrouter(ref),
		"github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.VrouterSpec":                schema_pkg_apis_tf_v1alpha1_VrouterSpec(ref),
		"github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.VrouterStatus":              schema_pkg_apis_tf_v1alpha1_VrouterStatus(ref),
	}
}

func schema_pkg_apis_tf_v1alpha1_TungstenfabricConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TungstenfabricConfig is the Schema for the tungstenfabricconfigs API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.TungstenfabricConfigSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.TungstenfabricConfigStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.TungstenfabricConfigSpec", "github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.TungstenfabricConfigStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_tf_v1alpha1_TungstenfabricConfigSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TungstenfabricConfigSpec defines the desired state of TungstenfabricConfig",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_tf_v1alpha1_TungstenfabricConfigStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TungstenfabricConfigStatus defines the observed state of TungstenfabricConfig",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_tf_v1alpha1_Vrouter(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Vrouter is the Schema for the vrouters API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.VrouterSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.VrouterStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.VrouterSpec", "github.com/michaelhenkel/tungstenfabric-operator/pkg/apis/tf/v1alpha1.VrouterStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_tf_v1alpha1_VrouterSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VrouterSpec defines the desired state of Vrouter",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_tf_v1alpha1_VrouterStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VrouterStatus defines the observed state of Vrouter",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
